server:
  port: 8080

spring:
  application:
    name: student-service
  datasource:
    url: jdbc:postgresql://localhost:5432/student_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework: INFO
    com.training: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      courseServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      courseServiceRetry:
        maxAttempts: 5
        waitDuration: 1s
course:
  service:
    base-url: http://localhost:8085/courses

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

